#!/bin/sh
# postrm script for kamiwaza

set -e

# Remove the service
systemctl stop kamiwaza || true
systemctl disable kamiwaza || true
rm -f /etc/systemd/system/kamiwaza.service
systemctl daemon-reload

# Remove the installation directory
rm -rf /opt/kamiwaza

# Remove the symlink
rm -f /usr/bin/kamiwazad

# Reload systemd to update service status
systemctl daemon-reload

exit 0 